import {
  Playfair_Display,
  Inter,
  Dynalight,
  Bebas_Neue,
  Manrope,
} from 'next/font/google';
import './globals.css';
import { ViewTransitions } from 'next-view-transitions';
import Nav from './components/Nav/Nav';
import Preloader from './components/Preloader';

const playFair = Playfair_Display({
  variable: '--font-playfair',
  weight: ['400', '600', '700'],
  subsets: ['latin'],
});

const inter = Inter({
  weight: '400',
  variable: '--font-inter',
  subsets: ['latin'],
});

const manrope = Manrope({
  weight: ['400', '500', '600'],
  variable: '--font-manrope',
  subsets: ['latin'],
});

const dynalight = Dynalight({
  variable: '--font-dynalight',
  weight: '400',
  subsets: ['latin'],
});

const bebas = Bebas_Neue({
  variable: '--font-bebas',
  weight: '400',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body
          className={`
          ${dynalight.variable} 
          ${bebas.variable}
          ${inter.variable} 
          ${manrope.variable} 
          ${playFair.variable} `}
        >
          {/* <Preloader/> */}
          <Nav />
          {children}
        </body>
      </html>
    </ViewTransitions>
  );
}
